version: '3.8'
services:
    db:
        image: 'mariadb'
        container_name: db_docker_mariage
        restart: always
        volumes:
        -   db-data:/var/lib/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_mariage
        restart: always
        depends_on:
            -   db
        ports:
            -   8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    smtp:
        image: mailhog/mailhog
        container_name: mailhog_docker_mariage
        ports:
            - 25:1025
            - 0.0.0.0:8025:8025
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_mariage
        ports:
            - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        links:
            - db
            - smtp
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:

