monolog:
    handlers:
        main:
            #means only triggered when the action level is reached
            type:         fingers_crossed
            #means only triggered for 5xx HTTP code errors
            action_level: critical
            handler:      grouped
        streamed:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            max_files: 10
        #only if the records are unique over a given period of time
        deduplicated:
            type:    deduplication
            time: 60
            handler: symfony_mailer
        #combine handlers ( by mail and in a file server )
        grouped:
            type:    group
            members: [streamed, deduplicated]
        symfony_mailer:
            type:       symfony_mailer
            from_email: 'mariage.manon.xavier@gmail.com'
            to_email:   'mariage.manon.xavier@gmail.com'
            subject:    '[MARIAGE_MANON_XAVIER] An Error Occurred ON PRODUCTION !'
            formatter:  monolog.formatter.html
            content_type: text/html
